name: istio

on:
  push:
    paths:
      - '.github/workflows/istio.yml'
      - 'build/istio/**'
      - '!build/istio/*.md'
  pull_request:
    paths:
      - '.github/workflows/istio.yml'
      - 'build/istio/**'
      - '!build/istio/*.md'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/istio/.version)
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: armv7
          distribution: ubuntu18.04
          run: |
            apt-get install -y --no-install-recommends git make
            git clone --depth 1 ${VERSION} https://github.com/xunholy/istio.git .
            make docker
